### ISSUE TITLE
Target [GuzzleHttp\ClientInterface] is not instantiable while building [Vizir\KeycloakWebGuard\Services\KeycloakService].

### ISSUE THREAD

**Issue by Jenkiiz** [Vizir/laravel-keycloak-web-guard#1]
Hello,

I'm facing this error when trying to use the library.

Any Idea ? 

git repo : https://github.com/Jenkiiz/web_guard.git

**Comment by mariovalney** [comment]
Hey Jenkiiz!
How are you?

I guess we missed to add the Guzzle in AppProvider.

Can you retry?
I added it to repo code.

**Comment by Jenkiiz** [comment]
Hey !
Tried with the new version, Auth login form is still here and getting another error now :
Call to undefined method Vizir\KeycloakWebGuard\Auth\Guard\KeycloakWebGuard::attempt()

I forgot a line somewhere I think

**Comment by mariovalney** [comment]
No. It's everything OK if you [follow the README](https://github.com/Vizir/laravel-keycloak-web-guard/blob/master/README.md).

The intent of this project is to be a complete auth system to routes guarded by Keycloak.

This way, Laravel Auth system will not work with that.

You are able to implement your User model and create your own User Provider to manage Laravel stuff, but to make Keycloak work as "Facebook Login button" more work will be needed.

**Comment by mariovalney** [comment]
> Tried with the new version, Auth login form is still here and getting another error now :
> Call to undefined method Vizir\KeycloakWebGuard\Auth\Guard\KeycloakWebGuard::attempt()

Attempt is used by Laravel's authentication to try to login the user into guard with credentials.
In Keycloak, this is the [Resource Owner Password Credentials Flow](https://www.keycloak.org/docs/latest/securing_apps/index.html#_resource_owner_password_credentials_flow) (or Direct Grant) and "it’s not recommended unless you absolutely need to."

So, the recommended way is to redirect user to Keycloak login page and proceed.

**Comment by Jenkiiz** [comment]
Seems to be working after deleting the defaut Auth files and controllers.
Also added the : 
Route::prefix('admin')
  ->middleware('keycloak-web')
  ->namespace($this->namespace)
  ->group(base_path('routes/web.php'));

To have the right redirections
