### ISSUE TITLE
How to get user attributes like username, user id, etc?

### ISSUE THREAD

**Issue by nmbatingal** [Vizir/laravel-keycloak-web-guard#13]
Hello,

How can I fetch additional user attributes like user id, username data?

Thank you in advance!

Best,
Nars

**Comment by mariovalney** [comment]
From Keycloak? 

You can create your own User Model and extend [Models/KeycloakUser](https://github.com/Vizir/laravel-keycloak-web-guard/blob/master/src/Models/KeycloakUser.php) to add custom data to attributes like a regular model.

**Comment by nmbatingal** [comment]
Thank you for your response. I somewhat followed your FAQs and googled more references.

**Comment by gpedro** [comment]
check my solution #32
if you want another custom attribute, you need to add to mapper (keycloack configuration) and fillable (user model)
