### ISSUE TITLE
stuck on login loop

### ISSUE THREAD

**Issue by diegoscunha** [Vizir/laravel-keycloak-web-guard#14]
Hello,

I have a problem at login.

The moment I try to log in the login screen keeps loading and only enters when I update the page.

I followed the FAQ's guidelines but it didn't work.

**Comment by mariovalney** [comment]
Hi.

This page is on your domain or it's a Keycloak login page?

**Comment by diegoscunha** [comment]
Hi,
problem solved.

**Comment by mariovalney** [comment]
Hi. Would you please provider your solution?

**Comment by diegoscunha** [comment]
I don't know how to inform. I cleared the cache and it worked.
