### ISSUE TITLE
GuzzleHttp\ClientInterface issue

### ISSUE THREAD

**Issue by tharindarodrigo** [Vizir/laravel-keycloak-web-guard#20]
Hi,

Really appreciate you putting out this package.
I'm using Laravel 7
and 1.5.5 of this
![screencapture-community-test-2020-05-25-18_03_19](https://user-images.githubusercontent.com/9903811/82813139-17453400-9eb2-11ea-968c-217a5cf404ab.png)

Argument 1 passed to Vizir\KeycloakWebGuard\Services\KeycloakService::__construct() must implement interface GuzzleHttp\ClientInterface, null given (View: /home/vagrant/code/community/resources/views/welcome.blade.php)

And I'm trying this on homestead with Keycloak running on docker
Appreciate it if you can help me out with this.

**Comment by mariovalney** [comment]
Hi. Sounds like it's duplicated from #19 

I'm going to check it out today.
Thanks for reporting.
