### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ahmedusama250** [Vizir/laravel-keycloak-web-guard#23]
How can I handle permissions individually without roles?

**Comment by ahmedusama250** [comment]
I made a pull request to can handle this.

**Comment by mariovalney** [comment]
Hi. What you mean by permission?

**Comment by ahmedusama250** [comment]
Go to my pull request and you will understand. I mean scopes as named in keycloak

**Comment by mariovalney** [comment]
@ahmedusama250 that's not how #opensource community works.

Anyway, thanks for your contribution.
I'll check when I have time.
