### ISSUE TITLE
Looping of callback for authenticated user.

### ISSUE THREAD

**Issue by sumit290785** [Vizir/laravel-keycloak-web-guard#25]
i faced a problem where user is authenticated on another application via keycloak and when i login to my app it loops into authentication and login and result into error page. As per the debugging done, when  i login from my app callback comes with query whereas when my app reach to keycloak when user is already authenticated it send it back with # prepend to query in place of ?. please tell me as it logsout frequently as it doesn't know where to redirect the user if he is already logged in.
thank you

**Comment by mariovalney** [comment]
Hi.

> when user is already authenticated it send it back with # prepend to query in place of ?.

Would you please provide this URL?

> please tell me as it logsout frequently as it doesn't know where to redirect the user if he is already logged in.

I'm sorry. I wasn't able to understand.

**Comment by sumit290785** [comment]
Have two apps using  same client. When logging to one app and try to log I nto other then second app start looping between callback and login

**Comment by mariovalney** [comment]
Hi. I guess i figured out your problem:

Each app should have a "client" from keycloak.
If you keep the same client for two apps, one will "stole" session from another.

**Comment by mariovalney** [comment]
Hi. Is it solved?
