### ISSUE TITLE
Unable to load the home page after the keycloak login is successfull.

### ISSUE THREAD

**Issue by Mounika-12** [Vizir/laravel-keycloak-web-guard#27]
Hi,

I have done all the changes to integrate keycloak to my laravel application and I am able to authenticate. Once the keycloak login is successful app should redirect to home page.
I have changed RouterServiceProvider.php like below.  Here the UI routes(using Vue) which I am triggering through web.php file is not getting loaded.  If I don't use keycloak-web middleware all the routes are working but there will no keycloak authentication.

```
protected function mapWebRoutes()
    {
        Route::prefix('admin')
            ->middleware('keycloak-web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    
        // Route::middleware('web')
        //     ->namespace($this->namespace)
        //     ->group(base_path('routes/web.php'));
    }
```

I am getting 404 not found for all the routes. Please help me regarding my issue.

**Comment by mariovalney** [comment]
Hi.
I'm not sure this is the problem, but we have to start from beginning.

In commented routes, there's no prefix.
Are you adding the prefix to path when using when keycloak-web?

**Comment by mariovalney** [comment]
Hi. Is it solved?
