### ISSUE TITLE
question: how i should relationship KeyCloakUser with other entities?

### ISSUE THREAD

**Issue by gpedro** [Vizir/laravel-keycloak-web-guard#32]
how i should relationship KeyCloakUser with other entities?

example:
a single user can have many Tasks.

**Comment by gpedro** [comment]
i found this article to add user uuid, but i need to check how to use this...
https://stackoverflow.com/a/45926963

**Comment by mariovalney** [comment]
Nice tutorial. Thanks.

**Comment by nicosalvadore** [comment]
@gpedro I'm trying to configure Eloquent relationships to other models in my app.
But get an error saying the relationship methods are not defined, for example : `Call to undefined method App\Models\User::belongsTo()`

The User model is correctly extending `KeycloakUser` as mentionned in your guide. Do you have an idea what could cause this ? Thanks

**Comment by nicosalvadore** [comment]
I'm asking because your original description on this issue was to link the User model with a Task model, but there is no relationship to the Task model in your code.

Thanks again !

**Comment by nomaniqbal0** [comment]
@mariovalney , @gpedro ,

I have followed your mentioned steps
1) code changes 
2) sync users table 
 still getting the error . eloquent function of user model is not working. 
Call to undefined method App\Models\User::hasMany()  or Call to undefined method App\Models\User::create()

Thanks

**Comment by nomaniq** [comment]
> *



> I'm asking because your original description on this issue was to link the User model with a Task model, but there is no relationship to the Task model in your code.
> 
> Thanks again !
> 
> edit : I skipped your `next steps` while reading your post. Your solution thus needs to sync the info in the local db ? And it's on the local DB that we would do our Eloquent relationships and queries ? @gpedro
> 
> sorry for spamming this closed issue :(




> 



Hi,

i am facing the same issue. i have implemented as mentioned . i have sync the database as well.
i am using keycloak with laravel cashier.

`**auth.php**`

 'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

'guards' => [

       'web' => [
            'driver' => 'keycloak-web',
            'provider' => 'users',
        ],

        
        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],
    ],


 'providers' => [
             
        'users' => [
            'driver' => 'keycloak-users',
            'model' => App\Models\User::class,
        ],
           

        'admins' => [
            'driver' => 'eloquent',
            'model' => App\Models\Admin::class,
        ],


    ],


`User.php model file`
------------------------------

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Vizir\KeycloakWebGuard\Models\KeycloakUser;
use Laravel\Cashier\Billable;
use App\Models\Subscription;

//use Laravel\Sanctum\HasApiTokens;


class User extends KeycloakUser
{
    use HasApiTokens, HasFactory, Notifiable, Billable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $primaryKey = 'user_id';

    protected $fillable = [
        'sub', 'name', 'email'
    ];

    /**
     * Get the value of the model's primary key.
     *
     * @return mixed
     */
    public function getKey()
    {
        return $this->attributes['sub'];
    }


}

when i am calling User::create or User::update , no eloquent function is working.
Please help

**Comment by mariovalney** [comment]
`KeycloakUser` only means to encapsulate data from Keycloak: it's not a Eloquent model.

You can check, [Laravel's User](https://github.com/laravel/laravel/blob/9.x/app/Models/User.php) extends `lluminate\Foundation\Auth\User as Authenticatable` [which extends a Eloquent Model](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Auth/User.php).

You have two options:

1. Implement these methods.
2. Use a regular Laravel user and implement the `retrieveByCredentials` method to get data from Keyclock in UserProvider.

_In both cases you should be aware that Eloquent Users must persist on Keycloak if you create it outside Keycloak._
