### ISSUE TITLE
Sync Keycloak users with Laravel database

### ISSUE THREAD

**Issue by gpedro** [Vizir/laravel-keycloak-web-guard#35]
how we can sync users to refer in local database as foreign key?

a sync command can be a cool option to solve that. 
add user data on login doesn't solve the problem, cuz if you need to refer a user than never logged you can't.

--
related to #34

**Comment by gpedro** [comment]
we should sync groups too? to make a company relationship?

**Comment by mariovalney** [comment]
It's a nice use case.
But we do not limit developers to use our UserProvider, so it should be a optional/plug-n-play feature.

Said that, I really liked making this a artisan command.
I'm just not sure this should be on main service class.

Are you thinking about keep this as a command to run always manually?

**Comment by gpedro** [comment]
I just registered the command. He doesn’t run automatically.

**Comment by gpedro** [comment]
so... should i create a sync command to user and groups with attributes? @mariovalney

**Comment by mariovalney** [comment]
I'm sorry. I'm not sure what you are asking.

**Comment by gpedro** [comment]
i mean... keycloak users and groups to sync and store on local database via sync command

**Comment by mariovalney** [comment]
Yes. 

As everything is optional/manual (in commands) no problem to add this possibility to developers.

**Comment by nicosalvadore** [comment]
@gpedro  @mariovalney 
I'm very interested in this feature, as I have to define relationships between users stored in keycloak and other entities in my app.
Let me know what can I do to get this merged !
Thank you

**Comment by gpedro** [comment]
> @gpedro @mariovalney
> I'm very interested in this feature, as I have to define relationships between users stored in keycloak and other entities in my app.
> Let me know what can I do to get this merged !
> Thank you

i will try back to finish that PR.

**Comment by nicosalvadore** [comment]
@gpedro thank you for the update :)

**Comment by gpedro** [comment]
guys, I recently tested the Cloudflare Access, it's a feature to prevent unauthorized access on pages. CF integrates with Keycloak using SAML. I guess is a better solution try to use same protocol instead this integration. Since CF uses, looks more mature and solid usage, so i found this: https://github.com/aacotroneo/laravel-saml2

---

 i will try search more about Keycloak integration on others languages to check how they made it and improve this repository
