### ISSUE TITLE
Authentication user provider [keycloak-users] is not defined.

### ISSUE THREAD

**Issue by ahmadsyamim** [Vizir/laravel-keycloak-web-guard#39]
I followed all the instructions, however i end up this error.

**Comment by mariovalney** [comment]
Which version (laravel and package) are you using?

**Comment by ahmadsyamim** [comment]
@mariovalney 
Sorry for late reply.

Laravel : v6.20.3
Package: Sorry. Not sure as i have changed to different library.

**Comment by lknite** [comment]
@ahmadsyamim what did you switch to?
