### ISSUE TITLE
[Keycloak Error] User cannot be authenticated

### ISSUE THREAD

**Issue by gorkagv** [Vizir/laravel-keycloak-web-guard#41]
#40 

The hasExpired function (KeycloakAccessToken) was returning true if $exp was greater than time(). The hasExpired function only should returning true when the $exp is less than or equal time(), that is, when the token has expired.

**Comment by lucca257** [comment]
i`m having the same problem

**Comment by mariovalney** [comment]
Hi!
I'm really sorry for the inconvenience and thanks for your PR. It's already fixed in 2.3.1.


_Note: Even with this problem the auth process should works, but will always refresh the access token._
