### ISSUE TITLE
Problem with Auth user

### ISSUE THREAD

**Issue by homeoftheunits** [Vizir/laravel-keycloak-web-guard#43]
Hey guys,

the middleware redirect to often to login.

I debug this, and in the Guard the setUser() sets the user, but the user is null in the KeycloakAuthenticated Middleware. Thats why the middleware redirects to /login, Keycloak says, user is logged, and so on. Until the Browser breaks with to many redirects.

Something should wrong in the Guard, and it's look like, that the user from keycloak doesn't attempt to Auth?

Answer from @mariovalney in https://github.com/Vizir/laravel-keycloak-web-guard/issues/42#issuecomment-770458570
How can i check the session? When i look in the session folder there are 16 session files for on process.

Cheers
Ralf

**Comment by homeoftheunits** [comment]
@mariovalney I see the accessToken in a session file. So it can't be an session Problem, right?

**Comment by mariovalney** [comment]
Hey. Because #44 I guess it's already OK?

**Comment by homeoftheunits** [comment]
Yes :)
