### ISSUE TITLE
Problem with Cors and web middleware

### ISSUE THREAD

**Issue by homeoftheunits** [Vizir/laravel-keycloak-web-guard#44]
Hey guys,

i have some Problem, with the logout when i add the web middleware:
```
            Route::middleware(['web', 'keycloak'])
                //->middleware('keycloak')
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));
```

I do this to make the route model binding work. When i do it like your documentation, the logout works, but not the model binding. With the web middleware, i got an cors error, login works correctly

Cheers
Ralf

**Comment by mariovalney** [comment]
Hi.

Would you please try to add logout to [VerifyCsrfToken](https://laravel.com/docs/8.x/csrf#csrf-excluding-uris) except?

**Comment by homeoftheunits** [comment]
Hi,

i add this, to the AuthController:
```
    public function __construct()
    {
        $this->middleware(\App\Http\Middleware\VerifyCsrfToken::class, ['except' => ['logout']]);
    }
 ```
 
 But the result is the same
 
 Cheers
 Ralf

**Comment by mariovalney** [comment]
I'm not sure this is the way.

Please try something like this:

```
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'logout',
    ];
}
```

**Comment by homeoftheunits** [comment]
same :(

**Comment by mariovalney** [comment]
Well.. let's try another approach.

I checked here and I'm able to use model binding on a controller with keycloak-web.
Here is my local environment: https://github.com/mariovalney/laravel-keycloak-web-guard-example

As you can see: https://github.com/mariovalney/laravel-keycloak-web-guard-example/blob/master/app/Http/Controllers/PageController.php#L59

**Comment by homeoftheunits** [comment]
It looks like, i solved this. We use inertiaJS, and the the Logout Button is an Inertia-Link Attribute. When i use an a-Attribute for the link, it works. Very strange
