### ISSUE TITLE
Problem In Keycloak Web Gate

### ISSUE THREAD

**Issue by viveksudalai** [Vizir/laravel-keycloak-web-guard#52]
Hi,
I am using Laravel and Vue.Js. Login and redirection is working fine. But i am getting following error when i try to use 
"abort_if(Gate::denies('keycloak-web','Client Admin'), Response::HTTP_FORBIDDEN, '403 Forbidden') " in my controller.
'Client Admin' is the Keycloak client Role.
      
message | "Argument  1 passed to  Spatie\\Permission\\PermissionRegistrar::Spatie\\Permission\\{closure}()  must be an instance of  Illuminate\\Contracts\\Auth\\Access\\Authorizable, instance of  Vizir\\KeycloakWebGuard\\Models\\KeycloakUser given, called in  /opt/lampp/htdocs/XXXweb/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php  on line 495"

exception | "TypeError"
file | "/opt/lampp/htdocs/XXXweb/vendor/spatie/laravel-permission/src/PermissionRegistrar.php"

And also i have role and their permission in my application. I want to use my application permission instead of keycloak resoureces.

auth.php

guards' => [
        'web' => [
            'driver' => 'keycloak-web',
            'provider' => 'keycloak-users',
        ],

        'api' => [
            'driver' => 'keycloak-web',
            'provider' => 'keycloak-users',
            'hash'     => false,
        ],
        

'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model'  => App\Models\User::class,
        ],
        'keycloak-users' => [
            'driver' => 'keycloak-users',
            'model' => Vizir\KeycloakWebGuard\Models\KeycloakUser::class,
        ],
    ],

**Comment by viveksudalai** [comment]
Would you please help me to resolve this?

**Comment by mariovalney** [comment]
Hi.

[Following the documentation](https://github.com/Vizir/laravel-keycloak-web-guard#keycloak-web-gate) it says: _to check user against one or more roles (and resources)_.

Is "Client Admin" a role? Would you please debug the token to check it?

```php
$token = KeycloakWeb::retrieveToken();

$roles = explode('.', $token['access_token'] ?? '');
$roles = base64_decode($roles[1] ?? '');
$roles = json_decode($roles, true);
$roles = $roles['resource_access'] ?? [];
$roles = $roles['account'] ?? [];
$roles = $roles['roles'] ?? [];

dd($roles);
```

**Comment by mariovalney** [comment]
Hi!

Sounds like our default model is not compatible with `spatie/laravel-permission`.

You can check "[How to implement my Model?](https://github.com/Vizir/laravel-keycloak-web-guard#how-to-implement-my-model)" to figured out how to create a compatible one.

Said that, I'm not sure you should use `spatie/laravel-permission` as it is used to manage roles and permissions: Keycloak is already able to do that. 

Maybe an alternative should be implement User as a Eloquent Model:

- How to [save user on login  callback](https://github.com/Vizir/laravel-keycloak-web-guard/issues/11#issuecomment-581977068).
- The [Eloquent Model example](https://github.com/Vizir/laravel-keycloak-web-guard/issues/32#issuecomment-691582873).
