### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by RewardRepo** [Vizir/laravel-keycloak-web-guard#7]
Hi,

I'm trying to integrate your keycloak web guard in my laravel project.
When I open the page in localhost (http:\\127.0.0.1:8080) I receive this error "[Keycloak Error] It was not possible to load OpenId configuration: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)" 

How can I resolved it? Could you help me?

Thanks,
Mattia

**Comment by mariovalney** [comment]
The **cURL error 60** sound to be a problem in your environment.
Check this, please: https://stackoverflow.com/a/23585500/5707025

Just a note:
> Your keycloak should be accessible by the laravel server connection.
> 
> For example, in my projects I use docker.
> So I need to expose a port and host from keycloak's container to laravel's one.
