### ISSUE TITLE
How to get login URL?

### ISSUE THREAD

**Issue by RewardRepo** [Vizir/laravel-keycloak-web-guard#8]
Hi,

I have some problem to configure the framework.
How can I configure the login form?

I follow you readme but now I don't know how to authenticate the user.

Thanks
Mattia

**Comment by mariovalney** [comment]
You will not use login form.

Following the readme you will get a "login URL" which will redirect to Keycloak login page.

**Comment by RewardRepo** [comment]
Hi Matio,

Thanks for the response! Yes, sorry We have the login form in our keycloack server but I don't know how to redirect the authentication.

Thanks,
Mattia

**Comment by mariovalney** [comment]
If you [protected a route](https://github.com/Vizir/laravel-keycloak-web-guard#how-can-i-protect-a-route) user should be redirected to login.

If you want the link to login (or another page) just use: `route('keycloak.login');`.

I hope this can help you.

**Comment by rickcwlng-hc** [comment]
Hi,

I'm currently trying to implement the package, but after I login I'm encountering and error. It redirects me too many times. What do you think is the issue?

Thank you for the amazing package!

**Comment by mariovalney** [comment]
@rickcwlng-hc what version are you using?
There was a problem before 1.5.2.

And Keycloak uses session to keep the access_token, check you can store data on session (from request to another).

**Comment by mariovalney** [comment]
@rickcwlng-hc I moved your comment to a new issue. Let's work there, ok? :)

**Comment by RewardRepo** [comment]
Thanks for the response.
Last question, how can I retrive the user information when I come back from the login form? Our server response is a JWT.

Thanks,
Mattia

**Comment by mariovalney** [comment]
You don't need to do this.

This package take care of persist session and [you can use the Auth Guard methods](https://github.com/Vizir/laravel-keycloak-web-guard#api) like [regular laravel login](https://laravel.com/docs/5.0/authentication#retrieving-the-authenticated-user).

Anyway, you can use the `Vizir\KeycloakWebGuard\Facades\KeycloakWeb` facade and `retrieveToken` method.

**Comment by RewardRepo** [comment]
Using KeycloakWeb::retrieveToken(); or Auth::user() the result is always null

**Comment by mariovalney** [comment]
So, token was not stored on session.

**Comment by RewardRepo** [comment]
Hi,

yes, in url I have "redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcallback."

**Comment by RewardRepo** [comment]
In function retrieveToken() I have the correct token but the return of the function is null

**Comment by RewardRepo** [comment]
I resolved the issue:

I changed the SESSION_DRIVER from "cookie" to "native"

**Comment by mariovalney** [comment]
Hi. [There's no "native" SESSION_DRIVER](https://github.com/laravel/laravel/blob/master/config/session.php#L1).

Maybe, using "native" (which is invalid) Laravel uses "file" driver.

I'll check it's all OK with "cookie" session, but it's recommended to use "file" anyway because will work well for the majority of applications.

**Comment by mariovalney** [comment]
Closing because sounds like everything is OK.

If you have any problem, please not hesitate to create a new issue.

Thanks.
