### ISSUE TITLE
Many redirects after sign-in

### ISSUE THREAD

**Issue by mariovalney** [Vizir/laravel-keycloak-web-guard#9]
Hi,

I'm currently trying to implement the package, but after I login I'm encountering and error. It redirects me too many times. What do you think is the issue?

Thank you for the amazing package!

_Originally posted by @rickcwlng-hc in https://github.com/Vizir/laravel-keycloak-web-guard/issues/8#issuecomment-577580915_

**Comment by mariovalney** [comment]
Hi @rickcwlng-hc ! How are you?
I created a new issue for you, OK?

Let's go: what version are you using?
There was a problem before 1.5.2.

And Keycloak uses session to keep the access_token, check you can store data on session (from request to another).

**Comment by rickcwlng-hc** [comment]
Thank you for the quick response Mario,

I'm using the latest version. I had a problem when I'm using the local ip address **(127.0.0.1:8000)**. Then I decided to deploy it on our test server which has a domain, then it works fine now. 

Will update here if I ever encounter any error in the future.

**Comment by mariovalney** [comment]
Nice to hear that.

:)
